name: Process Policy Definitions and Assignments

on:
  workflow_call:
    inputs:
      az_powershell_min_version:
        required: true
        type: string
      Ewoks_MG_Resource_Id:
        required: true
        type: string
      Platform_MG_Resource_Id:
        required: true
        type: string
      Connectivity_MG_Resource_Id:
        required: true
        type: string
      Identity_MG_Resource_Id:
        required: true
        type: string
      Management_MG_Resource_Id:
        required: true
        type: string
      Landing_Zones_MG_Resource_Id:
        required: true
        type: string
      Corp_MG_Resource_Id:
        required: true
        type: string
      Online_MG_Resource_Id:
        required: true
        type: string
      Decommisioned_MG_Resource_Id:
        required: true
        type: string
      Sandbox_MG_Resource_Id:
        required: true
        type: string

jobs:
  deploy-policy-definitions-and-assignments:
    runs-on: [self-hosted, linux]

    env:
      az_powershell_min_version: ${{ inputs.az_powershell_min_version }}
      top_management_resource_group_id: ${{ inputs.Ewoks_MG_Resource_Id }}
          
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v3

      - uses: azure/login@v1
        name: Azure OIDC login
        with:         
          tenant-id: ${{ secrets.TENANT_ID }}
          client-id: ${{ secrets.CLIENT_ID }}
          allow-no-subscriptions: true
          enable-AzPSSession: true
      
      - uses: azure/arm-deploy@v1 
        name: Assign custom policy definitions
        id: assignPolicyDefinitions
        with:
          scope: managementgroup
          region: westeurope
          managementgroupid: ${{ inputs.Ewoks_MG_Resource_Id }}
          template: modules/policy/assignment/alzDefault/alzDefaultPolicyAssignments.bicep
          parameters: >
            modules/policy/assignment/alzDefault/parameters/alzDefaultPolicyAssignments.parameters.all.json
            parTopLevelManagementGroupPrefix="Ewoks"
            Top_MG_Resource_Id="${{ inputs.Ewoks_MG_Resource_Id }}"
            Platform_MG_Resource_Id="${{ inputs.Platform_MG_Resource_Id }}"
            Connectivity_MG_Resource_Id="${{ inputs.Connectivity_MG_Resource_Id }}"
            Identity_MG_Resource_Id="${{ inputs.Identity_MG_Resource_Id }}"
            Management_MG_Resource_Id="${{ inputs.Management_MG_Resource_Id }}"
            Landing_Zones_MG_Resource_Id="${{ inputs.Landing_Zones_MG_Resource_Id }}"
            Corp_MG_Resource_Id="${{ inputs.Corp_MG_Resource_Id }}"
            Online_MG_Resource_Id="${{ inputs.Online_MG_Resource_Id }}"
            Decommisioned_MG_Resource_Id="${{ inputs.Decommisioned_MG_Resource_Id }}"
            Sandbox_MG_Resource_Id="${{ inputs.Sandbox_MG_Resource_Id }}"
            parLogAnalyticsWorkSpaceAndAutomationAccountLocation="westeurope"
            parLogAnalyticsWorkspaceResourceId="${{inputs.LogAnalytics_Workspace_Id}}"
            parLogAnalyticsWorkspaceLogRetentionInDays="30"
            
