name: Deploy Central Logging

on:
  workflow_call:
    inputs:
      Subscription_Id:
        required: true
        type: string

jobs:
  deploy-custom-rbac-role-definitions:
    runs-on: [self-hosted, linux]
    
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v3

      - uses: azure/login@v1
        name: Azure OIDC login
        with:         
          tenant-id: ${{ secrets.TENANT_ID }}
          client-id: ${{ secrets.CLIENT_ID }}
          subscription-id: ${{ inputs.Subscription_Id }}
          enable-AzPSSession: true

      - uses: azure/arm-deploy@v1
        name: Create the Resource Group for logging
        id: resourceGroupLogging
        with:
          scope: subscription
          region: westeurope
          subscriptionId: ${{ inputs.Subscription_Id }}
          template: ARMtemplates/resourceGroup.json
          parameters: modules/logging/parameters/resourceGroup.parameters.json

      