name: Login to Azure

on:
  
  workflow_dispatch:
  push:
    branches:
      - 'master'
      - 'Gertjan'

jobs:
  deploy-management-groups:
    runs-on: [self-hosted, linux]

    env:
      az_powershell_min_version: ${{ vars.inputs.az_powershell_min_version }}

    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v3

      - uses: azure/login@v1
        name: Azure OIDC login
        with:         
          tenant-id: ${{ secrets.TENANT_ID }}
          client-id: ${{ secrets.CLIENT_ID }}
          allow-no-subscriptions: true
          enable-AzPSSession: true
      
      - shell: pwsh
        name: Ensure correct Az module is installed
        run: |
          if (Get-Module Az -ListAvailable | Where-Object { $_.Version -eq $env:az_powershell_min_version }) {
            Write-Host "Az module version $env:az_powershell_min_version is already installed"
            Import-Module Az -MinimumVersion $env:az_powershell_min_version
          }
          else {
              Write-Host "Az module version $env:az_powershell_min_version is going to be installed"
              Install-Module -Name Az -AllowClobber -Force -Scope CurrentUser -Repository PSGallery -MinimumVersion $env:az_powershell_min_version
          }